local gifts_categories = {
    "food",
    "drink",
    "medical",
    "tool",
    "device",
    "repair",
    "misc",
    "ammo",
}

local bad_gifts_table = {
    -- FOOD
    food = {
        "breadold",
        "conserva",
        "mutant_part_boar_chop",
        "sausage",
    },
    -- DRINK
    drink = {
        "cigar",
        "cigarettes",
        "cigarettes_lucky",
        "cigarettes_russian",
        "joint",
        "tobacco",
    },
    -- MEDICAL
    medical = {
        "bandage",
    },
    -- TOOL
    tool = {
        "batteries_dead",
        "bolts_pack",
        "box_matches",
    },
    -- REPAIR
    repair = {
        "glue_b",
        "gun_oil_ru",
        "sewing_thread",
    },
    -- MISC
    misc = {
        "ball_hammer",
        "broken_detector",
        "cards",
        "cutlery",
        "e_syringe",
        "jar",
        "picture_woman",
        "porn",
        "porn2",
        "radio2",
        "shovel_old",
        "underwear",
        "welding_goggles",
    },

    device = {
        "ball_hammer",
        "broken_detector",
        "cards",
        "cutlery",
        "e_syringe",
        "jar",
        "picture_woman",
        "porn"
    },

    -- AMMO
    ammo = {
        "ammo_12x70_buck",
        "ammo_9x18_pmm",
        "ammo_9x18_fmj",
        "ammo_9x19_pbp",
        "ammo_9x19_fmj",
    },
}

local normal_gifts_table = {
    -- FOOD
    food = {
        "beans",
        "bread",
        "chili",
        "chocolate",
        "conserva",
        "corn",
        "meat_boar",
        "meat_dog",
        "nuts",
        "sausage",
        "tomato",
        "tushonka",
    },
    -- DRINK
    drink = {
        "beer",
        "cigar",
        "cigar1",
        "cigar2",
        "cigar3",
        "cigarettes",
        "cigarettes_lucky",
        "cigarettes_russian",
        "energy_drink",
        "joint",
        "marijuana",
        "tobacco",
        "vodka",
        "vodka2",
        "water_drink",
    },
    -- MEDICAL
    medical = {
        "antirad",
        "bandage",
        "drug_sleepingpills",
        "medkit",
        "stimpack",
        "yadylin",
    },
    -- DEVICE
    device = {
        "detector_simple",
        "itm_pda_common",
    },
    -- TOOL
    tool = {
        "batteries_dead",
        "bolts_pack",
        "box_matches",
        "cooking",
        "grooming",
        "guitar_a",
        "harmonica_a",
        "journal",
        "kerosene",
        "roubles",
        "swiss_knife",
    },
    -- REPAIR
    repair = {
        "glue_a",
        "glue_b",
        "gun_oil_ru",
        "gun_oil_ru_d",
        "ramrod_tool",
        "rasp_tool",
        "sewing_kit_b",
        "sewing_thread",
        "sharpening_stones",
    },
    -- MISC
    misc = {
        "ball_hammer",
        "boots",
        "broken_detector",
        "cards",
        "cutlery",
        "duct_tape",
        "e_syringe",
        "flashlight_broken",
        "gloves",
        "grease",
        "hand_watch",
        "headlamp",
        "jar",
        "jewelry_box",
        "picture_woman",
        "porn",
        "porn2",
        "radio",
        "radio2",
        "rope",
        "shovel_old",
        "steel_wool",
        "underwear",
        "walkie",
        "welding_goggles",
    },
    -- AMMO
    ammo = {
        "ammo_11.43x23_fmj",
        "ammo_12x70_buck",
        "ammo_12x76_bull",
        "ammo_5.45x39_ep",
        "ammo_5.56x45_fmj",
        "ammo_7.62x39_fmj",
        "ammo_9x18_fmj",
        "ammo_9x18_pmm",
        "ammo_9x19_fmj",
        "ammo_9x19_pbp",
    },
}

local good_gifts_table = {
    -- FOOD
    food = {
        "beans",
        "bread",
        "chili",
        "chocolate",
        "conserva",
        "corn",
        "meat_boar",
        "meat_dog",
        "nuts",
        "sausage",
        "tomato",
        "tushonka",
    },
    -- DRINK
    drink = {
        "beer",
        "energy_drink",
        "joint",
        "marijuana",
        "mineral_water",
        "tea",
        "tobacco",
        "vodka",
        "vodka2",
        "vodka_quality",
        "water_drink",
    },
    -- MEDICAL
    medical = {
        "antirad",
        "bandage",
        "cocaine",
        "drug_anabiotic",
        "drug_antidot",
        "drug_booster",
        "drug_psy_blockade",
        "drug_radioprotector",
        "drug_sleepingpills",
        "glucose",
        "medkit",
        "medkit_army",
        "morphine",
        "stimpack",
        "yadylin",
    },
    -- DEVICE
    device = {
        "detector_simple",
        "itm_pda_common",
        "itm_pda_uncommon",
    },
    -- TOOL
    tool = {
        "batteries_dead",
        "bolts_pack",
        "box_matches",
        "cooking",
        "grooming",
        "guitar_a",
        "harmonica_a",
        "journal",
        "kerosene",
        "roubles",
        "swiss_knife",
    },
    -- REPAIR
    repair = {
        "glue_a",
        "glue_b",
        "glue_e",
        "gun_oil_ru",
        "gun_oil_ru_d",
        "ramrod_tool",
        "rasp_tool",
        "sewing_kit_a",
        "sewing_kit_b",
        "sewing_kit_h",
        "sewing_thread",
        "sharpening_stones",
        "solvent",
    },
    -- MISC
    misc = {
        "broken_detector",
        "cards",
        "grease",
        "hand_watch",
        "jewelry_box",
        "porn",
        "porn2",
        "radio",
        "radio2",
        "rope",
        "walkie",
        "welding_goggles",
    },
    -- AMMO
    ammo = {
        "ammo_11.43x23_fmj",
        "ammo_11.43x23_hydro",
        "ammo_12.7x55_fmj",
        "ammo_12x70_buck",
        "ammo_12x76_bull",
        "ammo_12x76_dart",
        "ammo_12x76_zhekan",
        "ammo_4.6x30_fmj",
        "ammo_5.45x39_ep",
        "ammo_5.45x39_fmj",
        "ammo_5.56x45_fmj",
        "ammo_7.62x39_fmj",
        "ammo_7.62x51_fmj",
        "ammo_9x18_fmj",
        "ammo_9x18_pmm",
        "ammo_9x19_fmj",
        "ammo_9x19_pbp",
        "ammo_357_hp_mag",
    },
}

local excellent_gifts_table = {
    -- FOOD
    food = {
        "chocolate",
        "mre",
        "nuts",
        "protein",
        "sausage",
        "tushonka",
    },
    -- DRINK
    drink = {
        "energy_drink",
        "joint",
        "marijuana",
        "mineral_water",
        "tea",
        "tobacco",
        "vodka",
        "vodka2",
        "vodka_quality",
        "water_drink",
    },
    -- MEDICAL
    medical = {
        "akvatab",
        "antirad",
        "bandage",
        "cocaine",
        "drug_anabiotic",
        "drug_antidot",
        "drug_booster",
        "drug_psy_blockade",
        "drug_radioprotector",
        "drug_sleepingpills",
        "glucose",
        "medkit",
        "medkit_army",
        "medkit_scientic",
        "morphine",
        "rebirth",
        "stimpack",
        "stimpack_army",
        "yadylin",
    },
    -- DEVICE
    device = {
        "detector_simple",
        "itm_pda_common",
        "itm_pda_uncommon",
        "itm_pda_rare",
    },
    -- TOOL
    tool = {
        "batteries_dead",
        "bolts_pack",
        "box_matches",
        "cooking",
        "grooming",
        "guitar_a",
        "harmonica_a",
        "journal",
        "kerosene",
        "roubles",
        "swiss_knife",
    },
    -- REPAIR
    repair = {
        "glue_a",
        "glue_b",
        "glue_e",
        "gun_oil_ru",
        "gun_oil_ru_d",
        "ramrod_tool",
        "rasp_tool",
        "sewing_kit_a",
        "sewing_kit_b",
        "sewing_kit_h",
        "sewing_thread",
        "sharpening_stones",
        "solvent",
    },
    -- MISC
    misc = {
        "cards",
        "grease",
        "hand_watch",
        "jewelry_box",
        "porn",
        "porn2",
        "radio",
        "rope",
        "shovel_mili",
        "synthrope",
        "tarpaulin",
        "walkie",
    },
    -- AMMO
    ammo = {
        "ammo_11.43x23_hydro",
        "ammo_12.7x55_ap",
        "ammo_12x76_bull",
        "ammo_12x76_dart",
        "ammo_12x76_zhekan",
        "ammo_4.6x30_fmj",
        "ammo_5.45x39_ap",
        "ammo_5.45x39_fmj",
        "ammo_5.56x45_fmj",
        "ammo_5.56x45_ap",
        "ammo_5.56x45_ss190",
        "ammo_5.7x28_ss190",
        "ammo_5.7x28_ss195",
        "ammo_7.62x39_fmj",
        "ammo_7.62x39_ap",
        "ammo_7.62x51_fmj",
        "ammo_7.62x51_ap",
        "ammo_7.62x54_7h1",
        "ammo_9x18_fmj",
        "ammo_9x18_ap",
        "ammo_9x19_fmj",
        "ammo_9x19_ap",
        "ammo_9x39_ap",
        "ammo_357_hp_mag",
    },
}




-- choose a random gift from the array
function get_random_gift(category)

    local selected_category = category or "any"
    local current_friendship_stage = gfcmod.get_current_friendship_stage()
    local selected_gifts_table = {}
    
    if selected_category and selected_category == "any" then
        selected_category = gifts_categories[math.random(#gifts_categories)]
    end
    
    if current_friendship_stage and current_friendship_stage == "bad" then
        selected_gifts_table = bad_gifts_table[selected_category] or {}
    
    elseif current_friendship_stage and current_friendship_stage == "normal" then
        selected_gifts_table = normal_gifts_table[selected_category] or {}
   
    elseif current_friendship_stage and current_friendship_stage == "good" then
        selected_gifts_table = good_gifts_table[selected_category] or {}
    
    elseif current_friendship_stage and current_friendship_stage == "excellent" then
        selected_gifts_table = excellent_gifts_table[selected_category] or {}
    else
        selected_gifts_table = bad_gifts_table[selected_category] or {}
    end

    for k, v in pairs(selected_gifts_table) do
        --printdbg(v)
    end
    return selected_gifts_table[math.random(#selected_gifts_table)]

end